rm(list=ls())
install.packages ("pheatmap")
install.packages ("ggplot2")
library (pheatmap)
library (ggplot2)
data <- read.table ("cycling Neu.txt",header=T,row.names=1,sep="\t")
dim (data)
data= log2(data +1)
head (data)
p <- pheatmap (data)
p <- pheatmap (data, scale="row", border=T, cluster_cols = T, cluster_rows = T, show_rownames=F, show_colnames=T, color = colorRampPalette(c("DarkSlateGray1", "White", "Red"))(50))
p <- pheatmap (data, scale="row", border=T, cluster_cols = T, cluster_rows = T, show_rownames=F, show_colnames=T, color = colorRampPalette(c("Dark blue", "White", "Red"))(50),legend=F)
sample <- read.delim("sample circRNA.txt", row.names = 1, sep = "\t", check.names = F)
head(sample)
annotation_col<-read.table("sample circRNA.txt",header=T,sep="\t",row.names=1)
annotation_col<- as.data.frame(annotation_col)
View(annotation_col)
pheatmap (data, annotation_col = annotation_col)
pheatmap(data, scale="row", annotation_col = annotation_col)
ann_colors<- list(sample =c(health="#a4a4a4", sepsis="#b20101", COVID="#cc6600"))
p <- pheatmap (data, scale="row", annotation_col = annotation_col, annotation_colors = ann_colors, border=T, border_color="#4f4f4f", cluster_cols = F, cluster_rows = T, clustering_distance_rows="correlation", show_rownames=T, show_colnames=F, color = colorRampPalette(c("DarkSlateGray1","white","red"))(80),legend=T, legend_breaks=c (-1.5,0,1.5), fontsize_row=12, treeheitht_col=40, treeheight_row=40, annotation_legend = T)
