install.packages ("pheatmap")
install.packages ("ggplot2")
library (pheatmap)
library (ggplot2)
rm(list=ls())
data <- read.table ("circRNA TPM.txt",header=T,row.names=1,sep="\t")
dim (data)
data= log2(data +1)
dim(data)
head (data)
p <- pheatmap (data)
p <- pheatmap (data, scale="row")
p <- pheatmap (data, scale="row", border=F, cluster_cols = T, cluster_rows = T, show_rownames=F, show_colnames=T, color = colorRampPalette(c("Dark blue", "White", "Red"))(50),legend=T, legend_breaks=c (-1,0,1))
p <- pheatmap (data, scale="row", border=F, cluster_cols = T, cluster_rows = T, show_rownames=F, show_colnames=T, color = colorRampPalette(c("Blue", "White", "Red"))(50),legend=T, legend_breaks=c (-2,0,2), fontsize_row=12, treeheitht_col=50, treeheight_row=45)
sample <- read.delim("sample circRNA.txt", row.names = 1, sep = "\t", check.names = F)
head(sample)
annotation_col<-read.table("sample circRNA.txt",header=T,sep="\t",row.names=1)
annotation_col<- as.data.frame(annotation_col)
View(annotation_col)
pheatmap (data, annotation_col = annotation_col)
pheatmap(data, scale="row", annotation_col = annotation_col)
p <- pheatmap (data, scale="row", annotation_col = annotation_col,border=F, cluster_cols = F, cluster_rows = T, clustering_distance_rows="correlation", show_rownames=F, show_colnames=T,cellwidth=45, cellheight=3,color = colorRampPalette(c("NavyBlue","white","red"))(80),legend=T, legend_breaks=c (-3,-2,-1,0,1,2,3), fontsize_row=24, treeheitht_col=20, treeheight_row=45, annotation_legend = T)
ann_colors<- list(sample =c(health="#a4a4a4", cov="#cc6600",sepsis="#b20101"))
p <- pheatmap (data, scale="row", annotation_col = annotation_col,annotation_colors = ann_colors, border=F, cluster_cols = F, cluster_rows = T, clustering_distance_rows="correlation", show_rownames=F, show_colnames=T, cellwidth=25, cellheight=0.8,color = colorRampPalette(c("#012386","white","#b20101"))(40),legend=T, legend_breaks=c (-2,-1,0,1,2), fontsize_row=24, treeheitht_col=20, treeheight_row=45, annotation_legend = T)

